# This file was *autogenerated* from the file IBETest.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_987654321234567890987654321234567890987654321234567890987654321234567890987654321234567890987654321234567890 = Integer(987654321234567890987654321234567890987654321234567890987654321234567890987654321234567890987654321234567890); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
sage.repl.load.load(sage.repl.load.base64.b64decode("aWJlLnNhZ2U="),globals(),False)

(p,q,P,Ppub,s) = Setup()
print("setup done")
ID = "LiuZheng"
dID = Extract(ID,p,q,s)
print("extract done")
M = _sage_const_987654321234567890987654321234567890987654321234567890987654321234567890987654321234567890987654321234567890 
C = Encrypt(p,q,P,Ppub,ID,M)
print(C)
MDe = Decrypt(p,q,C,dID,P)
print(MDe==M)

C = (C[_sage_const_0 ],C[_sage_const_1 ]+_sage_const_1 ,C[_sage_const_2 ])
try:
	Mwrong = Decrypt(p,q,C,dID,P)
except Exception, e:
	print(e)
else:
	print(Mwrong)
