# This file was *autogenerated* from the file AesGUI.sage
from sage.all_cmdline import *   # import sage library
_sage_const_40 = Integer(40); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5)
from Tkinter import *
sage.repl.load.load(sage.repl.load.base64.b64decode("QWVzQ0JDLnNhZ2U="),globals(),False)

def doAES():
	finpath = finEntry.get()
	foutpath = foutEntry.get()
	try:
		fin = open(finpath,'r')
		fout = open(foutpath,'w')
	except Exception, e:
		print("can't open file")
		return
	mode = select.get()
	IV = IVEntry.get()
	key = keyEntry.get()
	AesCBC(fin,fout,mode,IV,key)
	return

root = Tk()
root.title("AesCBC")
root.geometry('500x250')

#Fin
FinFrame = Frame(root,bd = _sage_const_5 )
FinFrame.pack()
Label( FinFrame, text="fin", width = _sage_const_10 ).pack(side = LEFT)
finEntry = Entry(FinFrame, width = _sage_const_40 , bd = _sage_const_5 )
finEntry.insert(_sage_const_0 ,"text.txt")
finEntry.pack(side = LEFT)
#Fout
FoutFrame = Frame(root,bd = _sage_const_5 )
FoutFrame.pack()
Label( FoutFrame, text="fout", width = _sage_const_10 ).pack(side = LEFT)
foutEntry = Entry(FoutFrame, width = _sage_const_40 , bd = _sage_const_5 )
foutEntry.insert(_sage_const_0 ,"encrypt.txt")
foutEntry.pack(side = LEFT)
#IV
IVFrame = Frame(root,bd = _sage_const_5 )
IVFrame.pack()
Label( IVFrame, text="IV", width = _sage_const_10 ).pack(side = LEFT)
IVEntry = Entry(IVFrame, width = _sage_const_40 , bd = _sage_const_5 )
IVEntry.insert(_sage_const_0 ,"0123456789abcdeffedcba987654325")
IVEntry.pack(side = LEFT)
#Key
KeyFrame = Frame(root,bd = _sage_const_5 )
KeyFrame.pack()
Label( KeyFrame, text="key", width = _sage_const_10 ).pack(side = LEFT)
keyEntry = Entry(KeyFrame, width = _sage_const_40 , bd = _sage_const_5 )
keyEntry.insert(_sage_const_0 ,"0f1571c947d9e8590cb7add6af7f6798")
keyEntry.pack(side = LEFT)
#mode select
modeFrame = Frame(root,bd = _sage_const_5 )
modeFrame.pack()
select = StringVar()
EncryptButton = Radiobutton(modeFrame, text="Encrypt", variable=select, value="e")
DecryptButton = Radiobutton(modeFrame, text="Decrypt", variable=select, value="d")
EncryptButton.pack(side = LEFT)
DecryptButton.pack(side = LEFT)
#confirm Button
buttonFrame = Frame(root,bd = _sage_const_5 )
buttonFrame.pack()
confirmButton = Button( buttonFrame, text = "Confirm", command = doAES)
confirmButton.pack()

root.mainloop()
