# -*- coding: utf-8 -*-
# This file was *autogenerated* from the file modpow.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
def mod_pow(b,n,m):
    if(n==_sage_const_1 ):
        return (b%m)
    a=mod_pow(b,n//_sage_const_2 ,m)
    if(n%_sage_const_2 ==_sage_const_0 ):
        return ((a*a)%m)
    else:
        return ((a*a*b)%m)

b=int(input("b:"))
while(True):    
    n=int(input("n:"))
    if(n>=_sage_const_0 ):
        break
    print("please input a non-negative integer")
m=int(input("m:"))
a=mod_pow(b,n,m)
print(a)
