# This file was *autogenerated* from the file monoKey.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1)
f = open("monoKey.txt",'w')

key = "liuzheng"
keylist=[]
p = ord('a')
for c in key:
	cp = chr(p)
	if(c not in keylist):
		f.write(cp+' '+c+'\n')
		p=p+_sage_const_1 
		keylist.append(c)

for c in range(ord('a'),ord('z')+_sage_const_1 ):
	cp = chr(p)
	c = chr(c)
	if(c not in keylist):
		f.write(cp+' '+c+'\n')
		p=p+_sage_const_1 
		keylist.append(c)

f.close()
