# -*- coding: utf-8 -*-
# This file was *autogenerated* from the file rand_gen.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
import random

f=open("input.txt",'w')         
i=_sage_const_10 
j=_sage_const_0 
while(j<_sage_const_9 ):                    #从i=10开始，生成1到i^2的随机数，并另i=i^2，循环9次
    i=i*i
    f.write(str(random.randrange(_sage_const_1 ,i,_sage_const_2 ))+'\n')
    j=j+_sage_const_1                                            #循环结束时，i=10^(2^9)
f.write(str(random.randrange(i+_sage_const_1 ,_sage_const_2 *i,_sage_const_2 ))+'\n')        #生成从i到2i之间的随机数，保证有大数
f.close()
