# This file was *autogenerated* from the file testSHA.sage
from sage.all_cmdline import *   # import sage library
sage.repl.load.load(sage.repl.load.base64.b64decode("U0hBMjU2LnNhZ2U="),globals(),False)

print(SHA256(""))
