# This file was *autogenerated* from the file CommonModAttack.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16)
sage.repl.load.load(sage.repl.load.base64.b64decode("a2V5R2VuLnNhZ2U="),globals(),False)
sage.repl.load.load(sage.repl.load.base64.b64decode("UlNBRW5jcnlwdC5zYWdl"),globals(),False)
sage.repl.load.load(sage.repl.load.base64.b64decode("Q29tbW9uTW9kLnNhZ2U="),globals(),False)

m = "1234567890123456789012345678901234567890123456789012345678901234567890"\
"1234567890123456789012345678901234567890123456789012345678901234567890"\
"1234567890123456789012345678901234567890123456789012345678901234567890"\
"1234567890123456789012345678901234567890123456789012345678901234567890"
m = long(m)

(p,q,e,d,n,phi_n) = keyGen()
(p,q,e1,d,n,phi_n) = keyGenGivenN(p,q,_sage_const_17 )			#e1 = 17
(p,q,e2,d,n,phi_n) = keyGenGivenN(p,q,(_sage_const_1 <<_sage_const_16 )+_sage_const_1 )	#e2 = 2^16+1

c1 = RSAEncrypt(m,e1,n)
c2 = RSAEncrypt(m,e2,n)

mAttack = commonMod(c1,e1,c2,e2,n)
print(mAttack)
